/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csye6200.userInterface.immunization;

import com.google.common.collect.Lists;
import csye6200.entity.Vaccine;
import csye6200.service.VaccineService;
import csye6200.service.impl.VaccineServiceImpl;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.util.List;
import java.util.stream.Collectors;

/**
 *
 * @author Administrator
 */
public class ManageImmunizationPanel extends javax.swing.JPanel {

    private JPanel rightPanel;
    /**
     * Creates new form ManageRegistrationPanel
     */
    public ManageImmunizationPanel(JPanel rightPanel) {
        initComponents();
        this.rightPanel = rightPanel;
        populateTable(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        immunizationTypeCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        immunizationTable = new javax.swing.JTable();

        setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Manage Immunization");

        immunizationTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Immunized Students", "Unimmunized Students" }));
        immunizationTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                immunizationTypeComboActionPerformed(evt);
            }
        });

        jButton1.setText("View Detail");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        totalLabel.setText("Total: 0");

        immunizationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Type", "Student ID", "Immunization Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(immunizationTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalLabel)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(500, 500, 500)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(430, 430, 430)
                                        .addComponent(immunizationTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(immunizationTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(totalLabel)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jButton1)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    /**
     * combo select
     * @param evt
     */
    private void immunizationTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_immunizationTypeComboActionPerformed
        // TODO add your handling code here:
        int i = immunizationTypeCombo.getSelectedIndex();
        populateTable(i);
    }//GEN-LAST:event_immunizationTypeComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void populateTable(int type){

        int rowCount = immunizationTable.getRowCount();

        DefaultTableModel model = (DefaultTableModel)immunizationTable.getModel();

        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        VaccineService vcService = new VaccineServiceImpl();
        List<Vaccine> list;
        if(type == 0){
            List<Vaccine> all = vcService.getAllVaccination();
            if(all==null || all.isEmpty()){
                return;
            }
            list = all.stream().filter((x)->{
                if(x.getVaccinationTime().getYear() == LocalDate.now().getYear()){
                    return true;
                }
                return false;
            }).collect(Collectors.toList());
        }else{
            List<String> unvaccinatedStudentsId = vcService.getUnimmunizedStudentsId();
            if(unvaccinatedStudentsId==null || unvaccinatedStudentsId.isEmpty()){
                return ;
            }
            list = Lists.transform(unvaccinatedStudentsId,(x)->{
                Vaccine vc = new Vaccine();
                vc.setType("");//vaccine type needed to be implemented
                vc.setStudentId(x);
                vc.setTimeDisplay("");
                return vc;
            });
        }
        if(list == null || list.isEmpty()){
            return;
        }
        for(Vaccine v : list) {
            Object row[] = new Object[model.getColumnCount()];
            row[0] = v.getType();
            row[1] = v.getStudentId();
            row[2] = v.getTimeDisplay();
            model.addRow(row);
        }
        totalLabel.setText("Total: "+list.size());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable immunizationTable;
    private javax.swing.JComboBox<String> immunizationTypeCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
