/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csye6200.userInterface.immunization;

import csye6200.constants.PanelConstants;
import csye6200.constants.Constants;
import csye6200.entity.Vaccine;
import csye6200.entity.Student;
import csye6200.facade.StudentFacadeService;
import csye6200.facade.dto.Result;
import csye6200.facade.impl.StudentFacadeServiceImpl;
import csye6200.service.StudentService;
import csye6200.service.impl.StudentServiceImpl;
import csye6200.userInterface.AbstractManagePanel;
import csye6200.userInterface.DetailPanel;
import csye6200.userInterface.Student.ViewPanel;
import java.awt.CardLayout;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author Administrator
 */
public class ManageImmunizationPanel extends AbstractManagePanel {

    private JPanel rightPanel;
    /**
     * Creates new form ManageRegistrationManagePanel
     */
    public ManageImmunizationPanel(JPanel rightPanel) {
        initComponents();
        this.rightPanel = rightPanel;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        isImmunized = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        immunizationTable = new javax.swing.JTable();
        VaccineType = new javax.swing.JComboBox<>();

        setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Manage Immunization");

        isImmunized.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Immunized Students", "Unimmunized Students" }));
        isImmunized.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isImmunizedActionPerformed(evt);
            }
        });

        jButton1.setText("View Detail");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        totalLabel.setText("Total: 0");

        immunizationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Type", "Student ID", "Immunization Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(immunizationTable);

        VaccineType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DTaP", "Polio", "Hib" }));
        VaccineType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VaccineTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalLabel)
                                .addGap(232, 232, 232)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(VaccineType, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(isImmunized, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isImmunized, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VaccineType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(totalLabel)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jButton1)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    public void populateTable(){
        populateTable(0,0);
    }

    /**
     * combo select
     * @param evt
     */
    private void isImmunizedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isImmunizedActionPerformed
        // TODO add your handling code here:
        int i = VaccineType.getSelectedIndex();
        int j = isImmunized.getSelectedIndex();
        populateTable(i,j);
    }//GEN-LAST:event_isImmunizedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             // TODO add your handling code here:
        int row = immunizationTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String id = (String)immunizationTable.getValueAt(row, 1);
        StudentService studentService = new StudentServiceImpl();
        Student student = studentService.getStudentByID(id);
        if(student == null){
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
         DetailPanel vp = new ViewPanel(rightPanel, studentService, student);
        removeExistPanel(vp.getClass().getName(),rightPanel);
        rightPanel.add(PanelConstants.VIEW_IMMUNIZATION_PANEL, vp);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.last(rightPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void VaccineTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VaccineTypeActionPerformed
        // TODO add your handling code here:
        int i = VaccineType.getSelectedIndex();
        int j = isImmunized.getSelectedIndex();
        populateTable(i,j);
    }//GEN-LAST:event_VaccineTypeActionPerformed

    public void populateTable(int type, int isImmunized){

        int rowCount = immunizationTable.getRowCount();

        DefaultTableModel model = (DefaultTableModel)immunizationTable.getModel();

        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        StudentFacadeService service = new StudentFacadeServiceImpl();
        String stringType = "";

        switch (type){
            case 0: stringType = Constants.VACCINE_TYPE_1;break;
            case 1: stringType = Constants.VACCINE_TYPE_2;break;
            case 2: stringType = Constants.VACCINE_TYPE_3;break;
        }
        boolean ifImmunized = (isImmunized==0? true:false);

        Result<List<Vaccine>> result = service.getUnimmunizedStudentsId(stringType, ifImmunized);
        if(!result.isSuccess())
            return;

        if(result.getData()==null || result.getData().isEmpty()){
                return ;
        }

        for(Vaccine v : result.getData()) {
            Object row[] = new Object[model.getColumnCount()];
            row[0] = v.getType();
            row[1] = v.getStudentId();
            row[2] = v.getTimeDisplay();
            model.addRow(row);
        }
        totalLabel.setText("Total: "+result.getData().size());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> VaccineType;
    private javax.swing.JTable immunizationTable;
    private javax.swing.JComboBox<String> isImmunized;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
